### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by SportPlusX** [huhaku/typecho_TpHtmlCache#2]
/huhaku/ 要不要外面的引号？希望code一下它。

cache给了777还是提示没权限？

**Comment by SportPlusX** [comment]
禁用插件提示：`Call to undefined function recursiveDelete()`

**Comment by SportPlusX** [comment]
完蛋，插件列表无法完全清理该项目了，怎么删除，最怕的就是TP出现这种问题。

**Comment by huhaku** [comment]
不用外面的引号,你可以试下强制删除插件目录再禁用插件

**Comment by huhaku** [comment]
> 完蛋，插件列表无法完全清理该项目了，怎么删除，最怕的就是TP出现这种问题。

不用外面的引号,你可以试下强制删除插件目录再禁用插件

**Comment by SportPlusX** [comment]
恢复数据库解决
